server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
        #server-addr: 192.168.111.144:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'
