server:
  port: 9527

spring:
  application:
    name: cloud-gateway

#需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能。
#############################新增网关配置###########################
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
#            - After=2021-06-06T20:50:08.577+08:00[Asia/Shanghai]
#            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
#            - Cookie=chocolate, ch.p
#            - Header=X-Request-Id, \d+

              # 带指定请求头的参数的CURL命令
#              curl http://localhost:9527/payment/lb -H "X-Request-Id:123"
              # 该命令相当于发get请求，且没带cookie
              #curl http://localhost:9527/payment/lb

              # 带cookie的
              #curl http://localhost:9527/payment/lb --cookie "chocolate=chip"

#    cloud:
#      gateway:
#        routes:
#          - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#            uri: http://localhost:8001          #匹配后提供服务的路由地址
#            #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#            predicates:
#              - Path=/payment/get/**         # 断言，路径相匹配的进行路由
#
#          - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#            uri: http://localhost:8001          #匹配后提供服务的路由地址
#            #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#            predicates:
#              - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
###################################################################
eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

#########################################################################

